<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "zwbisdrei_formgen"
 *
 * Auto generated by Extension Builder 2013-08-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => '(Sudhaus7) XLS Exporter',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Daniel Simon',
    'author_email' => 'dsimon@sudhaus7.de',
    'author_company' => 'Sudhaus7 GmbH',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '1.2.0',
    'constraints' => array(
        'depends' => array(
            'extbase' => '8.0-9.9.99',
            'fluid' => '8.0-9.9.99',
            'typo3' => '8.0-9.9.99',
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);
